modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="emeraldbreeze"
version="1.0"
displayName="Emerald Breeze"
credits="Thanks to: TurtyWurty, SilentChaos512"
authors="Elot and Alz"
description='''

'''

